-- #######################################################################################
-- HYPRLAND CONFIG — converted to the Lua config format introduced in Hyprland 0.55.
-- Hyprlang (the old hyprland.conf syntax) is deprecated as of 0.55; this file is loaded
-- from ~/.config/hypr/hyprland.lua instead.
-- Refer to the wiki for more information: https://wiki.hypr.land/Configuring/Start/
-- #######################################################################################

-- hl.config({ autogenerated = true }) -- remove/leave commented to silence the warning

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

---------------------
---- MY PROGRAMS ----
---------------------

local terminal = "kitty"
local fileManager = "thunar"
local menu = "wofi --show drun"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
-- hl.exec_cmd() spawns asynchronously, so no trailing "&" is needed.
hl.on("hyprland.start", function()
    -- Remove this if you don't use tts, this is just wasting system process
    hl.exec_cmd("~/scripts/smol-tts/tts-server.sh")

    -- Status bars, notifications, ydotoold, IME, hypridle
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("ydotoold")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("hypridle")

    -- Clean up temp files
    hl.exec_cmd("~/.config/hypr/scripts/archive_old_temp.sh")

    hl.exec_cmd("systemctl --user start hyprpolkitagent")

    -- Launch zen-browser silently on workspace 1
    hl.exec_cmd("zen-browser", { workspace = "1 silent" })

    -- Wallpaper
    hl.exec_cmd("hyprpaper")
    -- Alternative startup wallpaper sequence, left as reference:
    -- hl.exec_cmd("~/.config/hypr/paper_startup.sh && hyprpaper && hyprctl hyprpaper wallpaper ',/home/zt/Pictures/wallpapers/startup.webp'")

    -- Launch vesktop silently on workspace 2
    hl.exec_cmd("vesktop --enable-features=WaylandWindowDecorations --ozone-platform-hint=x11 --disable-gpu", { workspace = "2 silent" })

    hl.exec_cmd("rm -rf /home/zt/.config/obs-studio/.sentinel")

    hl.exec_cmd("obs --startreplaybuffer --disable-shutdown-check", { workspace = "10 silent" })
end)

hl.window_rule({
    name = "obs-ws10",
    match = { class = "com.obsproject.Studio" },
    workspace = "10",
})

hl.window_rule({
    name = "zen-ws1",
    match = { class = "zen" },
    workspace = "1",
})

hl.window_rule({
    name = "vesktop-ws2",
    match = { class = "vesktop" },
    workspace = "2",
})

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("__GL_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Note: permission changes require a Hyprland restart; not applied on-the-fly.

-- hl.config({
--     ecosystem = {
--         enforce_permissions = true,
--     },
-- })

hl.config({
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
})

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- See https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = 0xee1a1a1a,
        },

        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        -- enabled = yes, please :)
        enabled = false,
    },
})

-- Default curves, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 0.5, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only" — uncomment if you want that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({ name = "no-gaps-wtv1", match = { float = false, workspace = "w[tv1]" }, border_size = 0, rounding = 0 })
-- hl.window_rule({ name = "no-gaps-f1", match = { float = false, workspace = "f[1]" }, border_size = 0, rounding = 0 })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/
hl.config({
    dwindle = {
        preserve_split = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/
hl.config({
    master = {
        new_status = "master",
    },
})

----------------
---- MISC ------
----------------

hl.config({
    misc = {
        disable_splash_rendering = true,
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        enable_anr_dialog = false,
        -- render_unfocused_fps = 60,
    },
})

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout = "us, th",
        kb_variant = "",
        kb_model = "",
        -- kb_options = "grp:win_space_toggle,caps:hyper",
        kb_options = "grp:win_space_toggle",
        -- kb_rules = "",
        numlock_by_default = true,

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        scroll_factor = 1,

        touchpad = {
            natural_scroll = true,
            disable_while_typing = false,
        },
    },
})

-- gestures, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
-- hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.config({
    xwayland = {
        enabled = true,
        force_zero_scaling = true,
    },
})

---------------------
---- KEYBINDINGS ----
---------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind("SHIFT + " .. mainMod .. " + E", hl.dsp.exec_cmd("~/.config/hypr/scripts/thunar-cwd.sh"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + G", hl.dsp.window.pseudo()) -- dwindle
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("kitty --title note --directory ~/obsidian-vault note"))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("kitty --title note --directory ~/obsidian-vault note d"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("kitty --title ncmpcpp ncmpcpp"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("kitty --title pomoru pomoru"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("kitty --title calcurse calcurse"))
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("/home/zt/scripts/quick_capture/venv/bin/python /home/zt/scripts/quick_capture/capture.py"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("/home/zt/scripts/quick_capture/venv/bin/python /home/zt/scripts/quick_capture/record.py"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("/home/zt/scripts/quick_capture/venv/bin/python /home/zt/scripts/quick_capture/toggle_scene.py"))
hl.bind("SHIFT + KP_Prior", hl.dsp.exec_cmd("pkill waybar")) -- Hidden landmine or a killswitch for any mouse control

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("hyprlock"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + tab", hl.dsp.exec_cmd("/home/zt/scripts/smol-tts/tts-speak.sh"))
hl.bind(mainMod .. " + SHIFT + tab", hl.dsp.exec_cmd("/home/zt/scripts/smol-tts/tts.sh"))

hl.bind(mainMod .. " + KP_End", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/1.sh"'))
hl.bind(mainMod .. " + KP_Down", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/2.sh"'))
hl.bind(mainMod .. " + KP_Next", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/3.sh"'))
hl.bind(mainMod .. " + KP_Left", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/4.sh"'))
hl.bind(mainMod .. " + KP_Begin", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/5.sh"'))
hl.bind(mainMod .. " + KP_Right", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/6.sh"'))
hl.bind(mainMod .. " + KP_Home", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/7.sh"'))
hl.bind(mainMod .. " + KP_Up", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/8.sh"'))
hl.bind(mainMod .. " + KP_Prior", hl.dsp.exec_cmd('sh -c "~/scripts/hotkeys/9.sh"'))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "l" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "d" }))

hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "d" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "l" }))

hl.bind(mainMod .. " + s", hl.dsp.focus({ direction = "d" }))
hl.bind(mainMod .. " + w", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + d", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + a", hl.dsp.focus({ direction = "l" }))

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "l" }))

-- Better browser navigation experience, remove if unwanted
hl.bind("CTRL + q", hl.dsp.exec_cmd([[hyprctl activewindow -j | jq -e '.class=="zen" or .class=="google-chrome" or .class=="brave-browser"' && ydotool key 104:1 104:0]]))
hl.bind("CTRL + e", hl.dsp.exec_cmd([[hyprctl activewindow -j | jq -e '.class=="zen" or .class=="google-chrome" or .class=="brave-browser"' && ydotool key 109:1 109:0]]))

-- Switch workspaces with mainMod + [0-9], move windows with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Screenshot
hl.bind(mainMod .. " + PRINT", hl.dsp.exec_cmd("hyprshot -m window -m active -o ~/Pictures/screenshots"))
hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m output -m active -o ~/Pictures/screenshots"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot --freeze -m output -m region -o ~/Pictures/screenshots"))

-- Example special workspace (scratchpad)
-- hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
-- hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Lock
hl.bind(mainMod .. " + SHIFT + escape", hl.dsp.exec_cmd("hyprlock"))

-- Lenovo
-- hl.bind("$function + F5", hl.dsp.exec_cmd("brightnessctl set 10%-"))
-- hl.bind("$function + F6", hl.dsp.exec_cmd("brightnessctl set 10%+"))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e+0" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move = "20 monitor_h-120",
    float = true,
})

hl.window_rule({
    name = "obs-immediate",
    match = { class = "^(obs)$" },
    immediate = true,
})

hl.window_rule({
    name = "obs-noborder",
    match = { class = "^(obs)$" },
    border_size = 0,
})

hl.window_rule({
    name = "obs-render-unfocused",
    match = { class = "^(obs)$" },
    render_unfocused = true,
})

hl.window_rule({
    name = "steam-overlay-ws10",
    match = { class = "^steam_app_4127892909$", title = "^$" },
    workspace = "10",
})
