#!/bin/bash

WALL_DIR="$HOME/Pictures/wallpapers"
HYPAPER_CONF="$HOME/.config/hypr/hyprpaper.conf"
DEFAULT_WALLPAPER="startup"  # name without extension
EXTENSIONS=("jpg" "jpeg" "png" "webp")

# Clear and start the new config
echo "# Auto-generated by generate_hyprpaper.sh" > "$HYPAPER_CONF"

# Recursively preload all image files
find "$WALL_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | while read -r file; do
    echo "preload = $file" >> "$HYPAPER_CONF"
done

# Find default wallpaper (startup) in subdirectories
DEFAULT_FILE=""
for ext in "${EXTENSIONS[@]}"; do
    match=$(find "$WALL_DIR" -type f -iname "${DEFAULT_WALLPAPER}.${ext}" | head -n 1)
    if [[ -n "$match" ]]; then
        DEFAULT_FILE="$match"
        break
    fi
done

# Fallback in case the default file is missing
if [[ -z "$DEFAULT_FILE" ]]; then
    echo "⚠️ Default wallpaper not found. Falling back to first image..."
    DEFAULT_FILE=$(find "$WALL_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | head -n 1)
fi

# Apply default wallpaper to all monitors
echo "" >> "$HYPAPER_CONF"
echo "wallpaper = ,$DEFAULT_FILE" >> "$HYPAPER_CONF"

